### ISSUE TITLE
Release in TER

### ISSUE THREAD

**Issue by spoonerWeb** [medienreaktor/form_double_opt_in#13]
Hey,

I've found your cool extension in TER but was first disappointed that it's only supported for TYPO3 v8 and v9.
See: https://extensions.typo3.org/extension/form_doubleoptin

Then I saw that you released some versions with support of TYPO3 v10 and my question is why you're not releasing it in TYPO3 Extension Repository?

**Comment by tritum** [comment]
👍 for upload to TER.

**Comment by danielkestler** [comment]
Sorry to ask that, but is anybody really using TER nowadays? 

There were problems with extension name, namespaces and the TER extension key in the past, so we discontinued supporting TER. Now we don't have ownership of the extension key anymore and can not upload it. 

Probably won't do.

**Comment by spoonerWeb** [comment]
So, then you're out of scope of many integrators and developers. 🤷 

What kind of extension name and namespace problems did you have? I can't remember there were some issues.

**Comment by danielkestler** [comment]
I don't know the details anymore. There were namespace and extension name resolving issues with different TYPO3 versions that finally lead to a change in the extension name – and then, don't ask me why, we had to pull it from TER and now have obviously lost ownership of the extension key.

This extension is targeted at developers only. That's why a lot of the open issues / pull requests with features won't be merged as all this stuff is out of scope of this extension.
