### ISSUE TITLE
get error 

### ISSUE THREAD

**Issue by matin73** [medienreaktor/form_double_opt_in#2]
Hello,

I am not able to install extension. I get error:

Oops, an error occurred!
Class Medienreaktor\FormDoubleoptin\Controller\DoubleOptInController does not exist. Reflection failed. 

All caches and autoload were cleared. Also class can be found in autoload_classmap.php

**Comment by Nebucadnezar** [comment]
This is due to an error in ext_localconf.php (Line 8)
Change 'Medienreaktor.FormDoubleoptin' to 'Medienreaktor.FormDoubleOptIn'

**Comment by danielkestler** [comment]
Thanks for your feedback. Okay, this is strange and maybe seems to depend on the TYPO3 version. Which version of TYPO3 are you using?

**Comment by matin73** [comment]
I am using 8.7.x - but after installing github version it worked

**Comment by Nebucadnezar** [comment]
I am using typo3 9.5.11 and have installed latest version from Extension Repository (v 1.1.1)

I made the change in ext_localconf because typo3 resolved the namespace of the controller wrong. 
Medienreaktor\FormDoubleoptin\... should be Medienreaktor\FormDoubleOptIn\...

The configuration of the plugin in CamelCase solved the problem for me.
However, I am not sure whether the installation problem is directly related. As I said, I got the error message on the confirmation page where the plugin is embedded. Here the controller is called directly.

**Comment by Nebucadnezar** [comment]
I just noticed that the current version from github already has the configuration in CamelCase.
Maybe the typo3 TER version is not up to date?

**Comment by danielkestler** [comment]
Ah, you are right. We are no longer supporting TER, and for some reason, I am also no longer able to edit, update or delete the extension in TER (maybe due to the changed package name) – so I will close this for now and recommend to always use composer instead (this package is on packagist, of course).
